export const ProjectsData = [
  {
    id: 1,
    type: "Personal Project",
    name: "Code - Reviewer",
    tech: [
      "OpenAI",
      "NodeJS",
      "ExpressJS",
      "Axios",
      // "ExpressJS",
      // "PostgreSql",
      // "Prisma ORM",
      "REST Api",
      "ReactJS",
      // "NextJS",
      // "Redux",
      // "Redux Toolkit",
      "Tailwind Css",
      "Responsive",
      "Framer Motion",
      // "Docker",
    ],
    description: [
      "A Gemini Clone app built with React and REST APIs for real-time data management.",
      "Features a dynamic UI with seamless integration of React and REST API for smooth user interaction.",
    ],
    links: {
      live: "https://gemini-clone-xi-one.vercel.app/",
      github: "https://github.com/swarajphalke/gemini-clone",
    },
    image: "exclusive-store.png",
  },
  {
    id: 2,
    type: "Personal Project",
    name: "Gemini - Clone",
    tech: [
      // "TypeScript",
      "NodeJS",
      // "ExpressJS",
      // "PostgreSql",
      // "Prisma ORM",
      "REST Api",
      "ReactJS",
      // "NextJS",
      // "Redux",
      // "Redux Toolkit",
      "Tailwind Css",
      "Responsive",
      // "Docker",
    ],
    description: [
      "A Gemini Clone app built with React and REST APIs for real-time data management.",
      "Features a dynamic UI with seamless integration of React and REST API for smooth user interaction.",
    ],
    links: {
      live: "https://gemini-clone-xi-one.vercel.app/",
      github: "https://github.com/swarajphalke/gemini-clone",
    },
    image: "exclusive-store.png",
  },
  {
    id: 3,
    type: "Personal Project",
    name: "Weather Forecasting App",
    tech: ["Rest Api", "ReactJS", "Material-ui"],
    description: [
      "A weather app built with React and REST APIs, featuring real-time weather updates for any location.",
      " Provides a clean, responsive interface with dynamic data fetching and seamless user experience.",
    ],
    links: {
      live: "https://weather-app-brown-psi.vercel.app/",
      github: "https://github.com/swarajphalke/Weather-App",
    },
    image: "elixir-ui.png",
  },
  {
    id: 4,
    type: "Personal Project",
    name: "Lottery Game",
    tech: [
      // "NextJS",
      // "Tailwind Css",
      // "Redux Toolkit",
      "ReactJS",
      "NodeJS",
      // "ExpressJS",
      // "Socket.io",
    ],
    description: [
      "Developed a dynamic lottery game in React with an engaging and interactive user interface.",
      "Features random number generation and user-friendly design.",
    ],
    links: {
      live: "https://lottery-game-zeta.vercel.app/",
      github: "https://github.com/swarajphalke/Lottery-Game",
    },
    image: "code-collab.png",
  },
  {
    id: 5,
    type: "Personal Project",
    name: "Todo List",
    tech: [
      // "NextJS",
      // "Tailwind Css",
      // "Shadcn-ui",
      "NodeJS",
      "ReactJS",
      "Material-ui",
      // "ExpressJS",
      // "MongoDB",
      // "Strapi",
      // "Sanity",
    ],
    description: [
      "A responsive to-do list app built with React for efficient task management.",
      "Features real-time updates with add, edit, and delete functionality.",
    ],
    links: {
      live: "https://tudo-list.vercel.app/",
      github: "https://github.com/swarajphalke/TudoList",
    },
    image: "blog.png",
  },
  {
    id: 4,
    type: "Personal Project",
    name: "Note Taking App",
    tech: [
      "HTML",
      "CSS",
      "Javascript",
      // "ReduxToolkit",
      "Responsive",
    ],
    description: [
      "A responsive note-taking app built with HTML, CSS, and JavaScript for easy note management.",
      "Simple design with real-time updates and optional browser storage.",
    ],
    links: {
      live: "https://note-app-ruby-nu.vercel.app/",
      github: "https://github.com/swarajphalke/NOTE-APP",
    },
    image: "mytribe.png",
  },
];
